# Project information
site_name: 'Under Construction'
site_description: 'Welcome to the Poké Devs. We develop some amazing Pokémon stuff.'
site_url: 'https://pokedevs.github.io/pokedevs-website'
site_author: 'Sankarsan Kampa'

# Repository
repo_name: 'pokedevs-website'
repo_url: 'https://github.com/PokeDevs/pokedevs-website'
edit_uri: edit/master/docs/

# Copyright
copyright: 'Copyright &copy; 2017 - Sankarsan Kampa'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'red'
  language: 'en'
  font:
    text: 'Scope One'
    code: 'Source Code Pro'
  favicon: 'favicon.png'
  logo: 'assets/images/pokedevs.png'

extra_css:
  - 'assets/stylesheets/extra.css'

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/PokeDevs'
    - type: 'discord'
      link: 'https://discord.gg/7P4H3TY'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - toc:
      permalink: '#'
  - smarty

# Pages
pages:
  - Pokédex API:
    - Intro: 'index.md'
    - Reference: 'reference.md'
    - Usage Notes: 'usage_notes.md'
    - Libraries: 'libraries.md'
    - Resources:
      - Pokémon: 'resources/pokemon.md'
      - Categories: 'resources/categories.md'
      - Egg Groups: 'resources/egg-groups.md'
      - Evolution Stones: 'resources/evolution-stones.md'
      - Leagues: 'resources/leagues.md'
      - Types: 'resources/types.md'
      - Meta: 'resources/meta.md'
  - Information:
    - About: 'about.md'

# Development
dev_addr: '0.0.0.0:201'
